const defaultMeds = [
  { id: 1, time: '08:00', name: 'Aspirina', dose: '100mg - 1 comprimido', note: 'Tomar após o café da manhã', status: 'done', tone: '' },
  { id: 2, time: '12:30', name: 'Metformina', dose: '500mg - 1 comprimido', note: 'Com almoço', status: 'pending', tone: 'orange' },
  { id: 3, time: '18:00', name: 'Losartana', dose: '50mg - 1 comprimido', note: 'Com água', status: 'pending', tone: 'orange' },
  { id: 4, time: '22:00', name: 'Sinvastatina', dose: '20mg - 1 comprimido', note: 'Tomar antes de dormir', status: 'missed', tone: 'red' }
];
const now = new Date();
const state = { meds: JSON.parse(localStorage.getItem('medlembra-meds') || 'null') || defaultMeds, user: null, selectedId: 2, calendarYear: now.getFullYear(), calendarMonth: now.getMonth(), selectedDay: now.getDate(), fontScale: Number(localStorage.getItem('medlembra-font-scale') || 1), darkMode: localStorage.getItem('medlembra-dark-mode') === 'true', reminders: localStorage.getItem('medlembra-reminders') !== 'false' };
let sqliteDatabase;
const sqliteStorageReady = new Promise((resolve, reject) => { const request = indexedDB.open('medlembra-sqlite-storage', 1); request.onupgradeneeded = () => request.result.createObjectStore('files'); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); });
const $ = (selector) => document.querySelector(selector);
const screens = [...document.querySelectorAll('.screen')];

function save() { localStorage.setItem('medlembra-meds', JSON.stringify(state.meds)); }
async function readSqliteFile(storage) { return new Promise((resolve, reject) => { const request = storage.transaction('files').objectStore('files').get('medlembra.sqlite'); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); }
async function writeSqliteFile(storage, data) { return new Promise((resolve, reject) => { const transaction = storage.transaction('files', 'readwrite'); transaction.objectStore('files').put(data, 'medlembra.sqlite'); transaction.oncomplete = resolve; transaction.onerror = () => reject(transaction.error); }); }
async function initializeSqlite() { const storage = await sqliteStorageReady; const savedFile = await readSqliteFile(storage); const config = await window.initSqlJs({ locateFile: (file) => `https://cdnjs.cloudflare.com/ajax/libs/sql.js/1.10.3/${file}` }); sqliteDatabase = savedFile ? new config.Database(new Uint8Array(savedFile)) : new config.Database(); sqliteDatabase.run('CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, contact TEXT NOT NULL UNIQUE, password TEXT NOT NULL, birth_date TEXT NOT NULL, image BLOB, image_type TEXT)'); sqliteDatabase.run('CREATE UNIQUE INDEX IF NOT EXISTS users_contact_unique ON users (lower(contact))'); return storage; }
function getStoredUsers() { try { const users = JSON.parse(localStorage.getItem('medlembra-users') || '[]'); return Array.isArray(users) ? users.filter((user) => user && typeof user.contact === 'string') : []; } catch (error) { console.warn('Contas locais inválidas; iniciando lista vazia.', error); return []; } }
function saveStoredUsers(users) { localStorage.setItem('medlembra-users', JSON.stringify(users)); }
function userToStorage(user) { return { name: user.name, contact: user.contact, password: user.password, birthDate: user.birthDate, image: user.imageData || null, imageType: user.imageType || null }; }
function userFromStorage(user) { if (!user) return null; let image = null; try { image = user.image ? new File([dataUrlToBytes(user.image)], 'profile-image', { type: user.imageType || 'image/jpeg' }) : null; } catch (error) { console.warn('Imagem de perfil inválida; continuando sem imagem.', error); } return { ...user, image, imageData: typeof user.image === 'string' ? user.image : null, imageType: user.imageType || null }; }
function dataUrlToBytes(dataUrl) { const encoded = dataUrl.split(',')[1] || ''; const binary = atob(encoded); return Uint8Array.from(binary, (character) => character.charCodeAt(0)); }
function fileToDataUrl(file) { return new Promise((resolve, reject) => { if (!file) { resolve(null); return; } const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = () => reject(reader.error); reader.readAsDataURL(file); }); }
async function saveUserToDatabase() { if (state.user.image && !state.user.imageData && typeof state.user.image.arrayBuffer === 'function') { state.user.imageData = await fileToDataUrl(state.user.image); state.user.imageType = state.user.image.type; } const users = getStoredUsers(); const storedUser = userToStorage(state.user); const index = users.findIndex((user) => user.contact.toLowerCase() === state.user.contact.toLowerCase()); if (index >= 0) users[index] = storedUser; else users.push(storedUser); saveStoredUsers(users); }
async function createAccount(account) { state.user = account; await saveUserToDatabase(); const savedAccount = getUserCredentials(account.contact); if (!savedAccount || savedAccount.password !== account.password) throw new Error('A conta não foi confirmada na lista local.'); state.user = savedAccount; }
async function loadUserFromDatabase() { getStoredUsers(); }
function getUserCredentials(contact) { const normalizedContact = contact.trim().toLowerCase(); const user = getStoredUsers().find((item) => item.contact.toLowerCase() === normalizedContact); return userFromStorage(user); }
function renderAvatar() { document.querySelectorAll('[data-avatar]').forEach((avatar) => { avatar.textContent = ''; if (state.user?.image) { const image = document.createElement('img'); image.src = URL.createObjectURL(state.user.image); image.alt = `Foto de ${state.user.name || 'usuário'}`; avatar.append(image); } else { avatar.textContent = (state.user?.name || 'Dona Maria').split(' ').map((name) => name[0]).slice(0, 2).join('').toUpperCase(); } }); }
function showToast(message) { const toast = $('#toast'); toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 2200); }
function formatCurrentDateTime() { return new Intl.DateTimeFormat('pt-BR', { weekday: 'long', day: '2-digit', month: 'long', year: 'numeric', hour: '2-digit', minute: '2-digit' }).format(new Date()); }
function getCurrentMonthLabel() { return new Intl.DateTimeFormat('pt-BR', { month: 'long', year: 'numeric' }).format(new Date(state.calendarYear, state.calendarMonth, 1)); }
function renderCurrentDateTime() { const dateElement = $('#current-date'); if (dateElement) dateElement.textContent = formatCurrentDateTime(); }
function setDefaultMedicationTime() { const timeInput = $('#med-time-input'); if (timeInput && !timeInput.value) timeInput.value = new Date().toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' }); }
function navigate(screenId) { screens.forEach((screen) => screen.classList.toggle('active', screen.id === screenId)); if (screenId === 'home-screen') renderHome(); if (screenId === 'history-screen') { renderHistory(); renderCalendar(); } if (screenId === 'detail-screen') renderDetail(); if (screenId === 'profile-screen') renderProfile(); if (screenId === 'settings-screen') renderSettings(); window.scrollTo({ top: 0, behavior: 'smooth' }); }
function renderHome() { const userName = state.user?.name || 'Dona Maria'; const firstName = userName.split(' ')[0]; const doneCount = state.meds.filter((med) => med.status === 'done').length; const progress = state.meds.length ? Math.round(doneCount / state.meds.length * 100) : 0; $('#home-title').textContent = `Olá, ${firstName}`; $('.progress-card span').textContent = `Você tomou ${doneCount} de ${state.meds.length} medicamentos`; $('.progress-card b').textContent = `${progress}%`; $('#today-list').innerHTML = state.meds.map((med) => `<article class="med-card ${med.tone}" data-id="${med.id}"><div class="med-time">${med.time}</div><div class="med-info"><strong>${med.name}</strong><span>${med.dose}</span><span>${med.note}</span></div><div class="med-actions"><button class="status status-toggle ${med.status}" data-action="toggle" data-id="${med.id}" aria-label="Alternar status de ${med.name}">${med.status === 'done' ? 'TOMADO' : med.status === 'missed' ? 'PERDIDO' : 'PENDENTE'}</button><button class="med-arrow" aria-label="Ver detalhes">›</button></div></article>`).join(''); renderCurrentDateTime(); renderAvatar(); applyFontScale(); }
function renderDetail() { const med = state.meds.find((item) => item.id === state.selectedId) || state.meds[0]; if (!med) { $('#detail-content').innerHTML = '<p class="muted center">Nenhum medicamento cadastrado.</p>'; return; } const isDone = med.status === 'done'; $('#detail-content').innerHTML = `<div class="detail-hero"><div class="detail-icon">◉</div><h2>${med.name}</h2><p>Para controle do Diabetes</p></div><div class="detail-grid"><div class="detail-row"><span class="row-icon">◌</span><div><span>Dosagem</span><b>${med.dose}</b></div></div><div class="detail-row"><span class="row-icon">◷</span><div><span>Horário habitual</span><b>Todo dia às ${med.time}</b></div></div><div class="detail-row"><span class="row-icon">◉</span><div><span>Médico prescritor</span><b>Dr. Carlos Silva (Cardiologista)</b></div></div><div class="detail-row"><span class="row-icon">⌾</span><div><span>Farmácia de compra</span><b>Farmácia Pague Menos</b></div></div><div class="detail-row"><span class="row-icon">▤</span><div><span>Estoque atual</span><b>Restam 15 comprimidos</b></div></div></div><button class="primary-button wide-button" data-action="toggle" data-id="${med.id}">${isDone ? 'Marcar como não tomado' : 'Marcar como tomado'}</button><button class="danger-button wide-button" data-action="remove" data-id="${med.id}">Remover remédio</button>`; }
function renderHistory() { $('#history-list').innerHTML = state.meds.slice(0, 4).map((med) => `<div class="activity"><div class="activity-icon">◉</div><div><strong>${med.name} - ${med.dose.split(' - ')[0]}</strong><span>Tomou como estava previsto às ${med.time}</span></div></div>`).join(''); renderAvatar(); applyFontScale(); }
function renderCalendar() { const monthDate = new Date(state.calendarYear, state.calendarMonth, 1); const daysInMonth = new Date(state.calendarYear, state.calendarMonth + 1, 0).getDate(); const isSelectedMonth = state.calendarYear === now.getFullYear() && state.calendarMonth === now.getMonth(); if (state.selectedDay > daysInMonth || isSelectedMonth && state.selectedDay > now.getDate()) state.selectedDay = isSelectedMonth ? now.getDate() : 1; $('#calendar-days').innerHTML = Array.from({ length: daysInMonth }, (_, index) => { const day = index + 1; return `<button class="calendar-day ${day === state.selectedDay ? 'selected' : ''}" data-day="${day}" aria-label="Selecionar dia ${day} de ${getCurrentMonthLabel()}">${day}</button>`; }).join(''); $('#current-month').textContent = getCurrentMonthLabel(); $('#selected-date').textContent = `${state.selectedDay} de ${getCurrentMonthLabel()}`; }
function renderProfile() { const form = $('#profile-form'); if (!form) return; form.elements.name.value = state.user?.name || ''; form.elements.contact.value = state.user?.contact || ''; form.elements.birthDate.value = state.user?.birthDate || ''; const avatar = $('[data-profile-avatar]'); avatar.textContent = ''; if (state.user?.image) { const image = document.createElement('img'); image.src = URL.createObjectURL(state.user.image); image.alt = `Foto de ${state.user.name || 'usuário'}`; avatar.append(image); } else { avatar.textContent = (state.user?.name || 'Dona Maria').split(' ').map((name) => name[0]).slice(0, 2).join('').toUpperCase(); } applyFontScale(); }
function applyFontScale() { const textElements = document.querySelectorAll('p,h1,h2,h3,strong,span,label,button,input,select,textarea,a'); textElements.forEach((element) => { if (!element.dataset.baseFontSize) element.dataset.baseFontSize = getComputedStyle(element).fontSize; element.style.fontSize = `${parseFloat(element.dataset.baseFontSize) * state.fontScale}px`; }); }
function renderSettings() { const labels = { 0.9: 'Pequena', 1: 'Normal', 1.15: 'Grande', 1.3: 'Muito grande' }; document.documentElement.style.setProperty('--font-scale', state.fontScale); document.body.classList.toggle('font-large', state.fontScale === 1.15); document.body.classList.toggle('font-xlarge', state.fontScale === 1.3); document.body.classList.toggle('dark-mode', state.darkMode); $('#font-size-label').textContent = labels[state.fontScale] || 'Normal'; document.querySelector('[data-setting="dark-mode"]').classList.toggle('active', state.darkMode); document.querySelector('[data-setting="dark-mode"]').setAttribute('aria-checked', String(state.darkMode)); document.querySelector('[data-setting="reminders"]').classList.toggle('active', state.reminders); document.querySelector('[data-setting="reminders"]').setAttribute('aria-checked', String(state.reminders)); applyFontScale(); }

document.addEventListener('click', (event) => {
  const screen = event.target.closest('[data-screen]');
  if (screen) { navigate(screen.dataset.screen); return; }
  const day = event.target.closest('[data-day]');
  if (day) { state.selectedDay = Number(day.dataset.day); renderCalendar(); showToast(`Dia ${state.selectedDay} selecionado`); return; }
  const calendarAction = event.target.closest('[data-calendar]');
  if (calendarAction) { state.calendarMonth += calendarAction.dataset.calendar === 'next' ? 1 : -1; const visibleDate = new Date(state.calendarYear, state.calendarMonth, 1); state.calendarYear = visibleDate.getFullYear(); state.calendarMonth = visibleDate.getMonth(); state.selectedDay = 1; renderCalendar(); return; }
  const action = event.target.closest('[data-action]');
  if (action?.dataset.action === 'add') { navigate('add-screen'); return; }
  if (action?.dataset.action === 'toggle') {
    const med = state.meds.find((item) => item.id === Number(action.dataset.id));
    if (med) { med.status = med.status === 'done' ? 'pending' : 'done'; save(); showToast(`${med.name}: ${med.status === 'done' ? 'tomado' : 'não tomado'}`); if ($('#detail-screen').classList.contains('active')) renderDetail(); else renderHome(); }
    return;
  }
  if (action?.dataset.action === 'remove') { const med = state.meds.find((item) => item.id === Number(action.dataset.id)); if (med && window.confirm(`Remover ${med.name} da sua lista?`)) { state.meds = state.meds.filter((item) => item.id !== med.id); save(); state.selectedId = state.meds[0]?.id || null; showToast('Remédio removido'); navigate('home-screen'); } return; }
  const setting = event.target.closest('[data-setting]');
  if (setting) { if (setting.dataset.setting === 'dark-mode') { state.darkMode = !state.darkMode; localStorage.setItem('medlembra-dark-mode', state.darkMode); showToast(state.darkMode ? 'Modo escuro ativado' : 'Modo claro ativado'); } if (setting.dataset.setting === 'reminders') { state.reminders = !state.reminders; localStorage.setItem('medlembra-reminders', state.reminders); showToast(state.reminders ? 'Lembretes ativados' : 'Lembretes desativados'); } renderSettings(); return; }
  const fontAction = event.target.closest('[data-font]');
  if (fontAction) { const fontLevels = [0.9, 1, 1.15, 1.3]; const currentIndex = Math.max(0, fontLevels.indexOf(state.fontScale)); const nextIndex = fontAction.dataset.font === 'increase' ? Math.min(fontLevels.length - 1, currentIndex + 1) : Math.max(0, currentIndex - 1); state.fontScale = fontLevels[nextIndex]; localStorage.setItem('medlembra-font-scale', state.fontScale); renderSettings(); showToast('Tamanho da letra atualizado'); return; }
  const card = event.target.closest('.med-card');
  if (card) { state.selectedId = Number(card.dataset.id); navigate('detail-screen'); }
});
$('#login-form').addEventListener('submit', async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const feedback = $('#login-feedback'); feedback.textContent = ''; try { const user = getUserCredentials(String(form.get('contact') || '')); if (!user || user.password !== String(form.get('password') || '')) { feedback.textContent = 'CPF/e-mail ou senha inválidos. Crie uma conta antes de entrar.'; return; } state.user = user; navigate('home-screen'); } catch (error) { feedback.textContent = 'Não foi possível validar o acesso agora.'; console.error(error); } });
$('#profile-edit-image').addEventListener('change', (event) => { const image = event.target.files[0]; if (image) { state.user = { ...state.user, image, imageData: null }; saveUserToDatabase().then(() => { renderProfile(); renderAvatar(); showToast('Foto atualizada'); }); } });
$('#profile-form').addEventListener('submit', async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); state.user = { ...state.user, name: form.get('name'), contact: form.get('contact'), birthDate: form.get('birthDate') }; await saveUserToDatabase(); renderProfile(); renderHome(); showToast('Informações atualizadas'); });
$('#signup-form').addEventListener('submit', async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const feedback = $('#signup-feedback'); const name = String(form.get('name') || '').trim(); const contact = String(form.get('contact') || '').trim(); const password = String(form.get('password') || ''); const birthDate = String(form.get('birthDate') || ''); feedback.textContent = ''; if (!name || !contact || !password || !birthDate) { feedback.textContent = 'Preencha todos os campos obrigatórios.'; return; } try { if (getUserCredentials(contact)) { feedback.textContent = 'Já existe uma conta com este CPF/e-mail.'; return; } await createAccount({ name, contact, password, birthDate, image: null, imageData: null }); event.currentTarget.reset(); showToast('Conta criada e salva com sucesso'); navigate('home-screen'); } catch (error) { feedback.textContent = 'Não foi possível salvar a conta. Tente novamente.'; console.error(error); } });
$('#add-form').addEventListener('submit', (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); state.meds.push({ id: Date.now(), time: form.get('time'), name: form.get('name'), dose: form.get('dose'), note: form.get('instructions') || 'Conforme orientação médica', status: 'pending', tone: 'orange' }); save(); event.currentTarget.reset(); showToast('Medicamento salvo com sucesso'); navigate('home-screen'); });
loadUserFromDatabase().finally(() => { setDefaultMedicationTime(); renderSettings(); renderHome(); renderCurrentDateTime(); });
setInterval(renderCurrentDateTime, 30000);
